// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Services/Management/bound_services.proto
// </auto-generated>
// Original file comments:
// ---------------------------------------------------------------------------------------------
//  Copyright (c) Dolittle. All rights reserved.
//  Licensed under the MIT License. See LICENSE in the project root for license information.
// --------------------------------------------------------------------------------------------
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Dolittle.Services.Management {
  /// <summary>
  /// Represents all the bound gRPC services in the system
  /// </summary>
  public static partial class BoundServices
  {
    static readonly string __ServiceName = "dolittle.services.management.BoundServices";

    static readonly grpc::Marshaller<global::Dolittle.Services.Management.ServiceType> __Marshaller_dolittle_services_management_ServiceType = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.Services.Management.ServiceType.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dolittle.Services.Management.Services> __Marshaller_dolittle_services_management_Services = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.Services.Management.Services.Parser.ParseFrom);

    static readonly grpc::Method<global::Dolittle.Services.Management.ServiceType, global::Dolittle.Services.Management.Services> __Method_GetForServiceType = new grpc::Method<global::Dolittle.Services.Management.ServiceType, global::Dolittle.Services.Management.Services>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetForServiceType",
        __Marshaller_dolittle_services_management_ServiceType,
        __Marshaller_dolittle_services_management_Services);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dolittle.Services.Management.BoundServicesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of BoundServices</summary>
    [grpc::BindServiceMethod(typeof(BoundServices), "BindService")]
    public abstract partial class BoundServicesBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Dolittle.Services.Management.Services> GetForServiceType(global::Dolittle.Services.Management.ServiceType request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for BoundServices</summary>
    public partial class BoundServicesClient : grpc::ClientBase<BoundServicesClient>
    {
      /// <summary>Creates a new client for BoundServices</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BoundServicesClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BoundServices that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BoundServicesClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BoundServicesClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BoundServicesClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Dolittle.Services.Management.Services GetForServiceType(global::Dolittle.Services.Management.ServiceType request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetForServiceType(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Dolittle.Services.Management.Services GetForServiceType(global::Dolittle.Services.Management.ServiceType request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetForServiceType, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Dolittle.Services.Management.Services> GetForServiceTypeAsync(global::Dolittle.Services.Management.ServiceType request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetForServiceTypeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Dolittle.Services.Management.Services> GetForServiceTypeAsync(global::Dolittle.Services.Management.ServiceType request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetForServiceType, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BoundServicesClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BoundServicesClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BoundServicesBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetForServiceType, serviceImpl.GetForServiceType).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, BoundServicesBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetForServiceType, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dolittle.Services.Management.ServiceType, global::Dolittle.Services.Management.Services>(serviceImpl.GetForServiceType));
    }

  }
}
#endregion
